### ISSUE TITLE
Error: INSTALLATION FAILED 

### ISSUE THREAD

**Issue by phanidevavarapu** [kubeshop/helm-charts#259]
Any fresh installation of the testkube in my local K8's is failing due to helm nil pointer issue. 
I think is due to the new PR" https://github.com/kubeshop/helm-charts/pull/258/files#diff-b3d5a53daf2423ea63a61fbf1d77611d46673954cfe7cfcf6e8dd059204708e3 

❯ helm install --create-namespace my-testkube testkube/testkube
Error: INSTALLATION FAILED: template: testkube/charts/testkube-api/templates/deployment.yaml:36:26: executing "testkube/charts/testkube-api/templates/deployment.yaml" at <.Values.nats.secretName>: nil pointer evaluating interface {}.secretName

**Comment by vsukhin** [comment]
Hey, @phanidevavarapu We will check it out today

**Comment by exu** [comment]
Hey @phanidevavarapu I've reverted failing changes. Please try again.

**Comment by ramezhanna** [comment]
He @exu still facing the same issue using helm or testkube cli

**Comment by exu** [comment]
Hi @ramezhanna @phanidevavarapu we still checking out what's failing - bug is fixed but our build system for some strange reason is not refreshing helm charts.

**Comment by exu** [comment]
@ypoplavs I think it could be a flaw in our build pipelines

The edge-case was like following here: 
1. I've introduced bug in testkube-api helm chart
2. it was taken as someone bumped up testkube-api version and chart build was triggered automatically 
3. I've tried to fix code for testkube-api helm chart (only helm-charts repo) 
4. Helm chart for testkube-api is not bumped automatically on helm charts files change
5. Main helm chart had always previous build of testkube-api - based on previous build triggered by testkube main github repo.

**Comment by exu** [comment]
I'll try to force it manually to fix the issue

**Comment by exu** [comment]
Hi @ramezhanna @phanidevavarapu I think I was able to fix it manually 🎉

**Comment by phanidevavarapu** [comment]
Hi @exu, I am able to install it now, thanks.

**Comment by danil-smirnov** [comment]
Hi, is the fix in the repo already? I've just tried to install version `1.5.37` but it failed with the same message.

**Comment by exu** [comment]
Cool! closing issue then!
