### ISSUE TITLE
Allow image Docker registry redefining for the entire package

### ISSUE THREAD

**Issue by danil-smirnov** [kubeshop/helm-charts#273]
**Why should it be implemented?**

In many enterprise environments, image downloads are allowed from internal servers only due to security measurements. Now it's impossible to redefine image registries for all the charts, i.e. nats-io chart lacks this option (https://github.com/nats-io/k8s/issues/378).

**Describe the improvement**

Ideally it should be a global `global.imageRegistry` parameter to define it across all the charts, but at least a working `image.registry` parameter for every chart would help. Maybe all external charts could be adopted and installed from local folders rather than from remote repositories.
 
**Additional context**
Add any other context about the problem here if needed.

**Comment by vsukhin** [comment]
Thank you, Danil. Good points!

**Comment by danil-smirnov** [comment]
Hi @vsukhin 
I'm afraid this PR does nothing for this issue, as it only creates a secret for a particular registry while images still refer to the public registries and there is no way to redefine them globally.
Also mentioned above external subchart `nats` still doesn't support a registry parameter.
Because of this, we are unable to use Testkube helm charts in our organization.
Maybe you can check Bitnami charts to learn how to do this properly?

**Comment by vsukhin** [comment]
Ok, I will reopen this request, we will look at it later

**Comment by vsukhin** [comment]
It's almost done. But we're waiting for changes from NATs, if they implement them. If not, then we need to add thier chart to our repo
