### ISSUE TITLE
No options for adding extra env variables

### ISSUE THREAD

**Issue by qcloudy** [kubeshop/helm-charts#306]
I think an option is needed to add extra env variables. For example if you need to add a proxy envs

Example from bitnami charts:

```
## @param extraEnvVars Extra environment variables to add
## E.g:
## extraEnvVars:
##   - name: FOO
##     value: BAR
##
extraEnvVars: []
```

**Comment by vsukhin** [comment]
Thank you, @qcloudy We will chevck it out

**Comment by ypoplavs** [comment]
Hello @qcloudy, 
We have added option for extra env vars. Please check and let us know if we could help you with anything else.

**Comment by qcloudy** [comment]
@ypoplavs Thanks a lot
