### ISSUE TITLE
testkube-api-server cannot find host testkube-nats

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#319]
**Describe the bug**
Helm chart not properly running when installing, error in testkube-api-server pod

**To Reproduce**
1. Install helm chart (in this was done with argoCD)
2. See error `"caller":"bus/nats.go:29","msg":"error connecting to nats","error":"dial tcp: lookup testkube-nats on [redacted]: no such host","stacktrace":"github.com/kubeshop/testkube/pkg/event/bus. │
│ NewNATSConnection\n\t/build/pkg/event/bus/nats.go:29\nmain.main\n\t/build/cmd/api-server/main.go:198\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`
3. Name of nats resources is release-name-nats

**Expected behavior**
All containers are running properly, no placeholder name nats

**Version / Cluster**
- Which testkube version? latest
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?
 
**Additional context**
There is a possible workout, set `testkube-api-nats-uri="nats://release-name-nats"`

**Comment by f-helm** [comment]
Just realised after some investigation that this happened because `helmCharts.releaseName` was not set to testkube. So probably not a bug and can be closed.

**Comment by ypoplavs** [comment]
Hello @f-helm,

Please use `testkube` as release name for now. We're planning on restructuring our charts soon so that it wouldn't be so ambiguous.
