### ISSUE TITLE
webhook-cert-patch lacks node selector configurations

### ISSUE THREAD

**Issue by RomanBats** [kubeshop/helm-charts#333]
**Describe the enhancement you'd like to see**
"dpejcev/kube-webhook-certgen:1.0.6" does not support arm64 and in clusters, with mixed architecture, it is sometimes scheduled on arm64 nodes which end up failing with "exec /kube-webhook-certgen: exec format error".
Either upgrading kube-webhook-certgen to a more recent version that has multiplatform images or support node selector would be nice :)

**Comment by vsukhin** [comment]
Great note, thank you!

**Comment by vsukhin** [comment]
might be @ypoplavs can move it to kubeshop org and add arm64 to docker build

**Comment by ypoplavs** [comment]
Hello @RomanBats,
We have added node selector configuration and working on making our image multi-arch. Please install the latest version of our helm-charts. 

Let us know in case of any issues!

**Comment by RomanBats** [comment]
@ypoplavs, that is wonderful! Many thanks!
