### ISSUE TITLE
Namespace preference not working for testkube

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#337]
**Describe the bug**
When I set a namespace preference with kubectl config, requests without specifying --namespace with testkube does not work

**To Reproduce**
1. Install helm chart with kustomize values (https://json.schemastore.org/kustomization.json), use a custom namespace:

```
helmCharts:
  - name: testkube
     namespace: <insert-namespace-name-here>
     releaseName: testkube
     repo: https://kubeshop.github.io/helm-charts
```

3. Run `kubectl config set-context --current --namespace=<insert-namespace-name-here>`
4. Run `kubectl config view --minify | grep namespace:` to verify namespace was set
5. Run `kubectl testkube get tests --verbose`
6. See error
```
api/GET-testkube.ServerInfo returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"testkube-api-server\" not found","reason":"NotFound","details":{"name":"testkube-api-server","kind":"services"},"code":404}
'
error: services "testkube-api-server" not found

getting all test with execution summaries in namespace testkube (error: api/GET-[]testkube.TestWithExecutionSummary returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"testkube-api-server\" not found","reason":"NotFound","details":{"name":"testkube-api-server","kind":"services"},"code":404}
'
error: services "testkube-api-server" not found)
```

**Expected behavior**
Same output as when using `kubectl testkube get tests --namespace <insert-namespace-name-here>`

**Version / Cluster**
- Which testkube version? 1.7.17

**Comment by ypoplavs** [comment]
Closing the issue, please re-open if the issue still persists or contact us in [Slack] to get faster support. (https://testkubeworkspace.slack.com/join/shared_invite/zt-2arhz5vmu-U2r3WZ69iPya5Fw0hMhRDg#/shared-invite/email)
