### ISSUE TITLE
Service Monitor validation fails

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#363]
**Describe the bug**
Inbuilt service monitor yaml is incorrect

**To Reproduce**
1. Enable built in service monitor
2. Try to deploy
3. See error `error validating data: ValidationError(ServiceMonitor.spec): unknown field "port" in **com.coreos.monitoring.v1.ServiceMonitor.spec`**

**Expected behavior**
Deployment works
 
**Additional context**
See [ServiceMonitor API](https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html#spec-endpoints-2), port found under endpoint so more indentation needed

**Comment by vsukhin** [comment]
Thank you @f-helm Will pick it up after holidays

**Comment by ypoplavs** [comment]
Hello @f-helm,

We have fixed the typo and it should be working now. Please try and let us know if anything.

**Comment by f-helm** [comment]
Hi, I upgraded testkube to 1.8.35 and it works now, thanks.
