### ISSUE TITLE
What version are we installing?

### ISSUE THREAD

**Issue by sebagomez** [kubeshop/helm-charts#389]
It would be nice to have here in this repo, for every release of the Testkube Helm chart, what version of the other helm charts is also  installing. 

I'd like to see easily, it could be a description on the release, the versions of the dashboard, operator-controller-manager and api-server I'm installing when I pick testkube 1.9 for instance

**Comment by vsukhin** [comment]
Thank you @sebagomez Good suggestion!

**Comment by ypoplavs** [comment]
Hello @sebagomez,

Please let me know if this something you have in mind: [NOTES](https://github.com/kubeshop/helm-charts/blob/add-notes-389/charts/testkube/NOTES.md) or the format should be different?

**Comment by sebagomez** [comment]
That'd be awesome... I really don't care much about the format, that's great. Would that be the description of every helm chart release?

**Comment by ypoplavs** [comment]
@sebagomez could you please elaborate on the second point? Do you want to see a similar file in all sub-charts as well?

**Comment by ypoplavs** [comment]
Thank you for a detailed explanation @sebagomez! We will get to this early next week.

**Comment by ypoplavs** [comment]
hello @sebagomez!
Apologies for such a long reply! We did a major restructure of our git flow and added Changelog generation to every new testkube release. Now you will be able to see the changes in the description:
<img width="965" alt="Screenshot 2023-05-25 at 20 29 05" src="https://github.com/kubeshop/helm-charts/assets/45286051/69f87969-16ce-4a45-8c8a-30781ec8b063">
