### ISSUE TITLE
Readiness probe failed for the testkube-api-server pods

### ISSUE THREAD

**Issue by ashishkurian** [kubeshop/helm-charts#391]
**What is going wrong**
When trying to install the testkube helm chart v1.8.95 in my EKS cluster, the testkube-api-server pods are not starting as the Readiness and Liveness probes are failing

**To Reproduce**
I installed the helm chart by the following commands.

`helm dependency build
[Charts.zip](https://github.com/kubeshop/helm-charts/files/10570105/Charts.zip)
`
`helm install -f values-sreiously.yaml testkube ./charts/testkube-1.8.95.tgz --debug -n testkube-ashish`

**Expected behavior**
I expect that this command should let the necessary pods to be in a running state.

**Version / Cluster**
- testkube version: v1.8.95
- EKS cluster
- EKS kubernetes version: 1.23

**Screenshots**

![image](https://user-images.githubusercontent.com/16349403/216355044-d280d13e-3eaf-4c0a-a86b-b517bed8a24e.png)

 
**Additional context**
I even tried to edit the deployment that creates these pods and still the pods are not coming up into a running state.

The files that I used are attached.

**Comment by vsukhin** [comment]
hey @ashishkurian can  you please run `kubectl logs testkube-api-server -n testkube-ashish` to see some server logs?

**Comment by ashishkurian** [comment]
Hi @vsukhin. It looks like the readiness/liveness probe was not the actual issue. I had nats disabled and in the container logs, it said 'no nats server found'.

Now I enabled the nats server and now the pod is running.

![image](https://user-images.githubusercontent.com/16349403/216384200-170132cf-6d46-47da-b585-4161056d4c78.png)

**Comment by vsukhin** [comment]
great! yes, we need nats
