### ISSUE TITLE
Testkube API endpoint configure

### ISSUE THREAD

**Issue by robervexcel** [kubeshop/helm-charts#394]
**Describe the bug**
I deployed the helm chart version 1.9.4 and apparently all is perfect, but when I want to change the Testkube API endpoint from gui option I received `"Could not receive data from the specified api endpoint"` I tried with http and https, with `/results/v1` and without it with` "service_name +"."+ service_namespace + ".svc.cluster.local" `, etc

**To Reproduce**
1. helm install testkube testkube/testkube -f my-values.yaml --create-namespace --namespace testkube --version 1.9.4
2. all pods are up except `testkube-dashboard-test-connection` and `testkube-dashboard-test-connection` with error `wget: bad address 'testkube-operator:80'` in log pod and the other with:

```
Connecting to testkube-api-server:8088 (172.20.201.170:8088)
wget: can't connect to remote host (172.20.201.170): Connection refused
```

**Expected behavior**
I want to see my test results

**Version / Cluster**
- Which testkube version? helm chart version `1.9.4`
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) `EKS` (AWS)
- What Kubernetes version? `1.23`

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
![image](https://user-images.githubusercontent.com/83281606/216590823-e1a38fdd-e103-4ed9-b55f-319e32b887b2.png)

 
**Additional context**
I use the default namespace `testkube` and I use nginx internal load balancer

my-values.yaml in chart:

```
testkube-dashboard:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: my-nginx
    hosts:
    - testkube.miurl.com
  apiServerEndpoint: https://testkube.myurl.com/results/v1 #not working ## tried with http://testkube-api-server.testkube.svc.cluster.local/results/v1 without success

testkube-api:
  uiIngress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: my-nginx
    hosts:
    - testkube.myurl.com
  cliIngress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: my-nginx
    hosts:
    - testkube.myurl.com
```

**Comment by vsukhin** [comment]
Hey, @robervexcel Hope, you saw this guide https://kubeshop.github.io/testkube/using-testkube/UI/#configure-ingress-for-results-endpoint
We don't need to enable cli ingress, only testkube-api ui ingress and dashboard ingress as in a guide above.
Please make sure you properly exposed your Testkube api endpoint 
it should be available for requests as curl -v http://yourdomain.com/results/v1/info

**Comment by robervexcel** [comment]
Thanks for reply
> curl -v http://testkube.test-jx-preview.vexcelgroup.com/results/v1/info
*   Trying X.X.X.170:80...
* TCP_NODELAY set
* Connected to myURL (X.X.X.170) port 80 (#0)
> GET /results/v1/info HTTP/1.1
> Host: testkube.test-jx-preview.vexcelgroup.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 03 Feb 2023 12:00:29 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3476
< Connection: keep-alive
< Last-Modified: Wed, 01 Feb 2023 17:09:10 GMT
< Vary: Accept-Encoding
< ETag: "63da9cb6-d94"
< Accept-Ranges: bytes

Yes it's available :/ but in my dashboard GUI I receive the error

Is it necessary to perform some test before? (I think that need some test to show...)

**Comment by vsukhin** [comment]
Sounds like, something is wrong with ingress config. You get html content, when it should return a small json object

**Comment by robervexcel** [comment]
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-testkube-api-server-testkube
  namespace: testkube
  resourceVersion: '394515385'
  generation: 3
  creationTimestamp: '2023-02-03T08:57:51Z'
  labels:
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/version: 1.9.1
    gitops.jenkins-x.io/pipeline: namespaces
    helm.sh/chart: testkube-api-1.9.1
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      XXXX
    kubernetes.io/ingress.class: nginx-private
    meta.helm.sh/release-name: testkube
  managedFields:
    - manager: nginx-ingress-controller
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2023-02-03T08:57:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      subresource: status
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2023-02-03T09:24:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:kubernetes.io/ingress.class: {}
            f:meta.helm.sh/release-name: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
    - manager: node-fetch
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2023-02-03T11:05:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:rules: {}
  selfLink: >-
    /apis/networking.k8s.io/v1/namespaces/testkube/ingresses/ui-testkube-api-server-testkube
status:
  loadBalancer:
    ingress:
      - hostname: >-
          XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX.amazonaws.com
spec:
  rules:
    - host: testkube.myurl
      http:
        paths:
          - path: /results/(v\d/executions.*)
            pathType: Prefix
            backend:
              service:
                name: testkube-api-server
                port:
                  number: 8088
`

Do you think something is wrong? I only change the ingresclass and URL name in default values of helm chart

**Comment by vsukhin** [comment]
yes, /results/(v\d.*)

**Comment by robervexcel** [comment]
Thank you for your response

Something is wrong here in this case -> https://github.com/kubeshop/helm-charts/blob/16798c87c9613101f967897a9b3c1095ff7500eb/charts/testkube/values.yaml#L199

Anyway, I received the same error:

![image](https://user-images.githubusercontent.com/83281606/216910794-7feb78c9-0bf3-4cf8-93f2-a3758a01474a.png)

**Comment by vsukhin** [comment]
and same curl response?

**Comment by ypoplavs** [comment]
Also could you please add `path: /` to dashboard Ingress as well? Also what do you see when you describe Ingress resources? 
`kubectl describe ingress name -n testkube`?

**Comment by ashishkurian** [comment]
Hi @ypoplavs . Unfortunately I am also experiencing the same problem.

![image](https://user-images.githubusercontent.com/16349403/216946115-acc7c145-73b7-416f-826c-6f985262cc5c.png)

![image](https://user-images.githubusercontent.com/16349403/216946177-b581f69d-a11f-42ca-9a36-4a8a71b33669.png)

I already have the `path: /` in my dashboard ingress

**Comment by robervexcel** [comment]
@vsukhin 

`> curl -v http://testkube.XXXXX.com/results/v1/info
*   Trying 10.100.162.170:80...
* TCP_NODELAY set
* Connected to testkube.XXXX.com (X.X.X.X) port 80 (#0)
> GET /results/v1/info HTTP/1.1
> Host: testkube.XXXXX.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 06 Feb 2023 10:23:32 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3476
< Connection: keep-alive
< Last-Modified: Wed, 01 Feb 2023 17:09:10 GMT
< Vary: Accept-Encoding
< ETag: "63da9cb6-d94"
< Accept-Ranges: bytes
`
@ypoplavs My ingress dashboard:
![image](https://user-images.githubusercontent.com/83281606/216948800-2867fc40-f596-4d82-90f1-7dc841ff213f.png)

**Comment by ypoplavs** [comment]
Please add this `path` to your testkube-api UI Ingress `path: /results/(v\d/.*)` .
Also can you please send me all your `values.yaml` file? I will run it on my set-up.

**Comment by robervexcel** [comment]
I made the change that you said but the error is the same 

My values are in the first post :)

**Comment by ypoplavs** [comment]
Please set `apiServerEndpoint: testkube.myurl.com/results` and check the Ingress for errors.
If no luck, let's schedule a call so we can go through the config together: https://calendly.com/yulia-poplavska/30min-1?month=2023-02
You can book a meeting through a Calendly for tomorrow and we can talk today if you're free.

**Comment by ashishkurian** [comment]
@ypoplavs : I still have the issue. 

Btw, I am using the AWS EKS cluster for the installation. Does that change something?

**Comment by ypoplavs** [comment]
@ashishkurian are you available for a call now?

**Comment by ashishkurian** [comment]
@ypoplavs : Yes. I can take a call now.

**Comment by ypoplavs** [comment]
Please join:  https://meet.google.com/aqq-mico-iqp

**Comment by ashishkurian** [comment]
@ypoplavs : Did you manage to test it on your aws setup?

**Comment by ypoplavs** [comment]
@ashishkurian is the MongoDB pod running?

**Comment by ashishkurian** [comment]
@ypoplavs : Yes the mongodb pod is running.

![image](https://user-images.githubusercontent.com/16349403/217287666-c10f7fd2-dd2a-4bad-b8c3-29d747bfcd93.png)

Also, there are no errors in the events for the mogodb pod

![image](https://user-images.githubusercontent.com/16349403/217287883-840c7354-a924-492a-b90d-502a9a5c4a3a.png)

**Comment by ypoplavs** [comment]
@ashishkurian I have replicated your configuration in my AWS cluster. Can we schedule a call to go through it?

**Comment by ashishkurian** [comment]
@ypoplavs How about 13.30 CET today?

**Comment by ypoplavs** [comment]
@ashishkurian sure
Video call link: https://meet.google.com/kqk-zriy-tsm

**Comment by ashishkurian** [comment]
@ypoplavs : I can confirm that the setup now works for me after our discussions. However, to help others with the resolution, I am commenting it here.

As I understand, we need to have a unique urls for both the dashboard and testkube-api end points. That is not the case if we are testing with minikube on local setup. Could this be somehow related to the AWS EKS setup I am using, that we need to have a unique url for both dasboard and testkube-api ?

Second thing, we need to specify the api url under the testkube-dashboard values >> testkube-dashboard.apiServerEndpoint

And, the annotations for the services are not necessary as I tested the installation without them and it still works

**Comment by ypoplavs** [comment]
Nice to hear that, @ashishkurian!
Yes, this is AWS-related setup. We cannot create the same DNS name in Route 53, thus, endpoints must be unique.

We are now writing a user guide that will ease installation of Testkube in AWS. 
Thank you for using Testkube :)

**Comment by robervexcel** [comment]
@ashishkurian If I understand, you put in testkube-dashboard.apiServerEndpoint -> myurl/results/v1 and this "myurl" must be different that testkube-api.ingress.hosts
Does is correct?

@ypoplavs I appreciate this guide :)

**Comment by ashishkurian** [comment]
@robervexcel : Yes. The 'myurl' must be the `testkube-api.uiIngress.hosts`

**Comment by robervexcel** [comment]
It doesn't work in my case with AWS ELB balancers

I tried 1.9.57 of helm chart, with and without https, incognito windows, differents browsers... etc
My values of chart:

```
testkube-dashboard:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - testkube.MYURL.com
  apiServerEndpoint: https://testkube-api.MYURL.com/results/v1

testkube-api:
  uiIngress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - testkube-api.MYURL.com
```

![image](https://user-images.githubusercontent.com/83281606/220392465-c313d9b9-f006-4064-a1ec-a193a8e09aed.png)

I tried to launch some tests to have "something" inside

![image](https://user-images.githubusercontent.com/83281606/220392678-9a7ab7f1-1ac0-4951-8196-d96c3d4669de.png)

**Comment by ashishkurian** [comment]
@robervexcel : As per my understanding, we need to use the `kubernetes.io/ingress.class: alb` as mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) to create the LBs in the aws.

Or do you already have the LBs created with these annotations? 

Otherwise the config looks good to me. Maybe I will advice the following suggestions for you to try.

* I had set `testkube-api.uiIngress.path: /results/v1` and `testkube-dashboard.ingress.path:/`
* I would try the urls differently like: `testkube-api.MYURL.com` and `testkube-dashboard.MYURL.com`
* Ingress annotations to make the ALBs external. In my case, they are internal.
* I do not see the annotations for the ingress like: `alb.ingress.kubernetes.io/certificate-arn` and `external-dns.alpha.kubernetes.io/hostname`
* For the api ingress, we need the health check path to be set using the annotatin: `alb.ingress.kubernetes.io/healthcheck-path: "/health"`

**Comment by ypoplavs** [comment]
@robervexcel please follow the guide below: https://testkube.io/blog/guide-to-deploying-testkube-on-aws
It's important to configure annotations like specified in a guide.

**Comment by robervexcel** [comment]
Works!!! in my case with ELB (classic load balancer) I only need to modified this:

https://github.com/kubeshop/helm-charts/blob/16798c87c9613101f967897a9b3c1095ff7500eb/charts/testkube/values.yaml#L199 to /result/v1 and use different URL,s for API and dashboard (why don't change you in values of chart by default?)

The guide it's perfect when I migrate to ALB in AWS ;) thank you!!
