### ISSUE TITLE
Container port on testkube-dashboard pods not configurable

### ISSUE THREAD

**Issue by ashishkurian** [kubeshop/helm-charts#395]
**Cannot make the container port on the testkube-dashboard pods as the readiness/liveness probes will fail**

The [testkube-dashboard service](https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-dashboard/templates/service.yaml#L20) is configured to use the http(80) as the target port for testkube-dashboard pods.

Thus I updated the values file to make the testkube-dashboard pods to expose port 80 as given below.

```
testkube-dashboard:
  enabled: true
  service:
    type: ClusterIP
    port: 80
```
But the testkube-dashboard pods are not coming to a running state as the liveness/readiness probes are failing. The liveness/readiness probes ports are not configurable as given [here](https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-dashboard/templates/deployment.yaml#L56)

Is this a missing feature or am I missing something here?

**Version / Cluster**
- testkube version : v1.8.95
- Kubernetes cluster: EKS
- Kubernetes version: v1.23

**Screenshots**
![image](https://user-images.githubusercontent.com/16349403/216612620-f13c7e55-c88a-4bda-9f21-7dceb6d08743.png)

**Comment by vsukhin** [comment]
thank you @ashishkurian let us check it out

**Comment by ypoplavs** [comment]
Hello @ashishkurian,
We have made a change in our helm charts so now you should be able to specify a service port for dashboard without any issues. Please try and let us know about the results.

**Comment by ashishkurian** [comment]
@vsukhin : Sorry for a slight confusion that I created by opening this issue. To simply explain my issue, I tried to use the port number 80 as the container port for the dashboard pods.

But if I do that, the readiness and liveness probe will never success and thus the pods will never come to a running state. I think this could be because the container image is blocking the readiness/liveness probes at any port except 8080.

The dashboard pods goes into a crashloopbackoff state as seen in the screen shots.

![image](https://user-images.githubusercontent.com/16349403/217008705-e540119e-449e-430c-b157-c8e0799a7a0b.png)

The pod events are as follows

![image](https://user-images.githubusercontent.com/16349403/217008846-4459f85a-8aa7-4af9-963b-b7d4a180bede.png)

Due to this issue, as I am using AWS eks, the ALB will never register a healthy target and thus the dasboard url will never come up.

![image](https://user-images.githubusercontent.com/16349403/217009103-140c422f-a68b-45f4-b70e-412c58e31b29.png)

So I think the container image need to be updated to accept the readiness/liveness probes at the port that is opened for the pods.

**Comment by ypoplavs** [comment]
Closed as resolved.

**Comment by ashishkurian** [comment]
After discussing with the developers, it is understood that the container port for the dasbboard pods should always be 8080.

@ypoplavs : As a suggestion, I would say to make the [container port](https://github.com/kubeshop/helm-charts/blob/42b03f63c684edaa4553379b5e0d4ab0100cb020/charts/testkube-dashboard/values.yaml#L95) of the dashboard pods to be static 8080 rather than configurable from the values file.

**Comment by ypoplavs** [comment]
Thank you for a suggestion, @ashishkurian! We will discuss this with a team.
