### ISSUE TITLE
Support setting image digests in all testkube images

### ISSUE THREAD

**Issue by michael-barker** [kubeshop/helm-charts#408]
Some images support setting the digest with `image.digest` while others do not.

https://github.com/kubeshop/helm-charts/pull/409

**Comment by ypoplavs** [comment]
hi @michael-barker,

`global.images.image` template doesn't allow us to set an image tag to chart's appVersion which we're currently doing. I suggest we extend each chart's template and include adding digest there, like
https://github.com/kubeshop/helm-charts/pull/412

Merged the PR. Please upgrade TK version to the latest one and enjoy :)
