### ISSUE TITLE
Image for pre-upgrade Job can't be overwritten

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/helm-charts#414]
Image for pre-upgrade Job can't be overwritten using --set Helm flag (or any other way)

**To Reproduce**
1. Run helm install on environment where Docker registry is not available
2. mongodb-upgrade job can't be done due to `ImagePullBackOff` error

**Expected behavior**
I can overwrite that value using helm --set flag

**Version / Cluster**
- 1.9.92
- Local kubernetes
 
**Additional context**
https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/templates/pre-upgrade.yaml#L26

**Comment by ypoplavs** [comment]
hi @michal-jagiello-tmpl,
we have added an option to override image for mongo job. Please upgrade Testkube to the latest version and let us know about the results.
