### ISSUE TITLE
securityContext duplication in minio template

### ISSUE THREAD

**Issue by rozner** [kubeshop/helm-charts#431]
**Describe the bug**
In the minio template the `securityContext` key is duplicated. It is both defined on line 112 and 117. 

**Version / Cluster**
- Which testkube version? 
introduced in `testkube-1.9.136`
 
**Additional context**
https://github.com/kubeshop/helm-charts/blob/577737d4a2ceb85be0f4d8cf0d5a07a67c115d92/charts/testkube-api/templates/minio.yaml#L112

**Comment by vsukhin** [comment]
thank you @rozner fixing our helm charts now

**Comment by rozner** [comment]
Thank you @vsukhin for taking this up so fast.

**Comment by dejanzele** [comment]
Nice catch @rozner , thanks for submitting the issue, a PR will be merged after validating.

**Comment by rozner** [comment]
I can confirm that it works and there aren't any more such issues. Flux is happy now :) Have a great day
