### ISSUE TITLE
Testkube-api-server Liveness/Readiness Faile

### ISSUE THREAD

**Issue by Jim0530** [kubeshop/helm-charts#441]
```
NAME                                                    READY   STATUS    RESTARTS        AGE
testkube-api-server-86dc8dc8b4-97v2b                    0/1     Running   7 (5m57s ago)   17m
testkube-dashboard-59497c8f8d-9l92c                     1/1     Running   0               17m
testkube-minio-testkube-7dddff9494-9qfh4                0/1     Pending   0               17m
testkube-dashboard-59497c8f8d-9l92c                     1/1     Running   0               17m
testkube-minio-testkube-7dddff9494-9qfh4                0/1     Pending   0               17m
testkube-mongodb-6475c59c5f-l9f8j                       0/1     Pending   0               17m
testkube-nats-0                                         3/3     Running   0               17m
testkube-nats-box-5789c4b55f-vxl7h                      1/1     Running   0               17m
testkube-operator-controller-manager-5fff8d9888-vv8s2   2/2     Running   0               17m
```
when i kubectl describe Pod/testkube-api-server, it has liveness/readiness issues. 
will minio & mongodb both in pending status cause testkube-api-server /health malfunctional???

**Comment by vsukhin** [comment]
hey @Jim0530 Yes, mongodb is critical dependency and minio is optional one. Testkube will not work without mongodb

**Comment by Jim0530** [comment]
Thanks! How should i fix the pod unbound issues?? Can i use our own mariadb instead of installing a new one?? Thanks!

**Comment by vsukhin** [comment]
hey, @Jim0530 You can either check logs for pending pods (either it's lack of resources or security constraints). Or you can use external MongoDb or might even DocumentDB in aws. At the moment we don't support SQL databases for stroing test execution results

**Comment by vsukhin** [comment]
if I understand correctly from other issue,  Testkube is up and running
