### ISSUE TITLE
TestTriggers webhook fails on testkube helm chart update with x509 certificate error

### ISSUE THREAD

**Issue by alexandrchumakin** [kubeshop/helm-charts#443]
**Describe the bug**
TestTriggers webhook throws the error on Testkube Helm Chart update [here](https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/webhook.yaml#L32): `name: vtesttrigger.kb.io`

**To Reproduce**
1. Setup "labels to labels" testkube TestTrigger
2. Update testkube helm release with a newest version

**Expected behavior**
Testkube should be updated accordingly, all dependent resources (tests, test suites, triggers, executors) should stay as is

**Version / Cluster**
- testkube helm release version 1.10.1
- Kubernetes cluster in Microsoft Azure
- Kubernetes version 1.23.5

**Additional context**
The error from Flux:
```
TestTrigger/{env}/{testTriggerName} dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "[vtesttrigger.kb.io](http://vtesttrigger.kb.io/)": failed to call webhook: Post "[https://{testKubeHost}/validate-tests-testkube-io-v1-testtrigger?timeout=10s](https://testkube-operator-webhook-service.{env}.svc/validate-tests-testkube-io-v1-testtrigger?timeout=10s)": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "nil1")
```

**Comment by TheBrunoLopes** [comment]
@dejanzele can you take a look when you have the time ?

**Comment by dejanzele** [comment]
@alexandrchumakin 
Can you tell me from which Testkube version did you update, and to which version did you update?

**Comment by alexandrchumakin** [comment]
@dejanzele 
we're deploying Testkube to our Kubernetes cluster using helm chart version [1.10.1](https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.10.1)

**Comment by dejanzele** [comment]
@alexandrchumakin were you doing a clean install or upgrading from a previous version?

**Comment by alexandrchumakin** [comment]
@dejanzele it only happens during every helm release upgrade, not for installation from scratch

**Comment by dejanzele** [comment]
Thank you @alexandrchumakin , I'll look into it and get back to you as soon as possible.
