### ISSUE TITLE
Pre-upgrade job image is not configurable

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/helm-charts#457]
**Describe the bug**
On environment where we use docker proxy testkube can't be deployed at all

**To Reproduce**
1. Try to install testkube on env where there is no direct internet connection
2. It fails on pre-hook job due to ImagePullBackOff error

**Expected behavior**
I can configure that or imageRepository (which is already used on global) is used

**Version / Cluster**
- Which testkube version? 1.10.400
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) local cloud

**Comment by TheBrunoLopes** [comment]
@ypoplavs @dejanzele this seems to be the error that I was also having.
I was trying to deploy Testkube in my minikube cluster and was getting this error. had to start a new minikube cluster to be able to deploy again. Just added this issue to the top of our backlog for the next release. thanks for reporting it @michal-jagiello-tmpl  ;)
