### ISSUE TITLE
MongoDB PreUpgradeHook does not take values override

### ISSUE THREAD

**Issue by jmrrcarvalho** [kubeshop/helm-charts#467]
**Describe the bug**
In case we want to override the image registry for the upgrade mongodb "preUpgradeHook" using another value other then the global one, the value is not taken in consideration when deploying the helm chart.

**To Reproduce**
1. Create a values.yaml file to override registry values
2. Set preUpgradeHook with a different value than [global][imageRegistry]
3. Deploy the Helm Chart
4. See that the Job is taking the value from the global imageRegistry

**Expected behavior**
The expectation is that the value set under the preUpgradeHook is taken in consideration the same way it happens with "testkube-operator" preUpgrade.

**Version / Cluster**
- Which testkube version? 1.11.15 
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.23

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

values-extra.yaml
`global:
  imageRegistry: remote-docker.artifactory.xxxxxxxxx.com
  annotations:
    app: testkube

preUpgradeHook:
  image:
    registry: k8s-gcr-docker-remote.artifactory.xxxxxxxxxx.com

testkube-operator:
  preUpgrade:
    image:
      registry: k8s-gcr-docker-remote.artifactory.xxxxxxxxxx.com`

By changing this line of code under "/testkube/templates/pre-upgrade" it picks up the value from the override (would be the same as under the testkube operator pre-upgrade):

from:
        `image: {{ include "global.images.image" (dict "imageRoot" .Values.preUpgradeHook.image "global" .Values.global) }}`
        
to:
       ` image: {{ include "global.images.image" (dict "imageRoot" .Values.preUpgradeHook.image) }}`

**Comment by ypoplavs** [comment]
hi @jmrrcarvalho!
we have modified the code to use `global` variable in order to override registries for all images. 

This change might be breaking for the users who already use `global`. Is it possible to push the image to your registry for the pre-upgrade jobs as well in this case?

**Comment by jmrrcarvalho** [comment]
Hi @ypoplavs ,

I understand that the change I have highlighted breaks who only use the `global` and may not be the solution. :)
Unfortunately on my case I cannot push the image to the same registry as this is controlled by the company I work for and for some reason they split it by "registry". :( 
That is the reason we are using the override on the values.yaml file for the preUpgradeHook

Would it possible that helm chart takes in consideration priorities? Like:

1st - override values per sub-chart
2nd - global values
3rd - original sub-chart values

**Comment by vsukhin** [comment]
Sure, thing. We try to cover the most common scenarios, but users always have something special ) In any case, we will be glad to add any improvement suggestions)
