### ISSUE TITLE
MultiNamespace

### ISSUE THREAD

**Issue by Jim0530** [kubeshop/helm-charts#469]
How can i select namespace for each tests/testsuites from dashboard??? or even create tests via CLI Tools (kubectl / testkube) ?

**Comment by vsukhin** [comment]
hey, @Jim0530 Good question. We work on CLI config multinamespace support this week
Dashboard should take namespace from api endpoint

**Comment by TheBrunoLopes** [comment]
Hello @Jim0530 you can do that on right now on Testkube Cloud
I would love to walk you through it, feel free to book a quick call at your convenience, if you want me to demo it for you ;) https://calendly.com/bruno-at-kubeshop/30min-1
