### ISSUE TITLE
Add labels from values.yaml global.labels to job template

### ISSUE THREAD

**Issue by plamen-kutinchev** [kubeshop/helm-charts#546]
We were able to deploy successfully testkube but we cannot run any tests due to label admission hook that needs everything running inside the cluster to have labels added. Can we add labels to the testkube job execution since right now I see errors like: 

`failed to execute test: execution failed: test execution failed: retry count exceeeded, there are no active pods with given id=6490134ee57f8ed2b1050030","status":500`

My guess would be that no labels are added to k8s job. With a hint I think labels needs to be added in those template files here: https://github.com/kubeshop/helm-charts/tree/develop/charts/testkube-api

**Comment by ypoplavs** [comment]
Merged [PR](https://github.com/kubeshop/helm-charts/pull/550)
