### ISSUE TITLE
STORAGE_ACCESSKEYID and STORAGE_SECRETACCESSKEY from Secret

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/helm-charts#553]
**Describe the enhancement you'd like to see**
Currently, there is no way to provide the storage access-key-id and secret-access-key from the secret kind. Having these values not come from a secret introduces a security challenge in my workflow. I use Flux [Helm Release](https://fluxcd.io/flux/guides/helmreleases/#define-a-helm-release) to manage Testkube installation and store the manifest in a Git repo. Anyone having access to the repo will be able to see the values. 

It'd be great if the helm chart loads the values from a secret if provided. 

I can take a stab and submit a pull request. 

https://github.com/kubeshop/helm-charts/blob/935a2934f35c573d146bae1278e972d112b3d8e0/charts/testkube-api/templates/deployment.yaml#L120-L121

https://github.com/kubeshop/helm-charts/blob/935a2934f35c573d146bae1278e972d112b3d8e0/charts/testkube-api/templates/deployment.yaml#L122-L123

**Comment by vsukhin** [comment]
Thank you @michaelsatish Good suggestion

**Comment by ypoplavs** [comment]
PR was merged https://github.com/kubeshop/helm-charts/pull/557 and will be released by the of the week.

**Comment by jrlost** [comment]
Unfortunately this fix just broke support for this: https://github.com/kubeshop/testkube/issues/3965
I think you should have instead inverted your logic, so apply the secretRef if the property has a value, otherwise just pass the old value across.

**Comment by vsukhin** [comment]
thank you @jrlost we will ask @ypoplavs to check

**Comment by ypoplavs** [comment]
Hello @jrlost! 
Thank you for bringing it to our attention. We have inverted the logic for the secrets in Minio and now the feature with AWS S3 storage should be working. Please upgrade to **v1.13.4** of the helm charts and let us know about the results.

**Comment by jrlost** [comment]
@ypoplavs it impacts https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube-api/templates/deployment.yaml#L152 as well

**Comment by jrlost** [comment]
@ypoplavs confirmed working, thank you
