### ISSUE TITLE
Load OAuth2 CLIENT_SECRET and COOKIE_SECRET from secret provider 

### ISSUE THREAD

**Issue by thehundt** [kubeshop/helm-charts#581]
**Describe the enhancement you'd like to see**
Currently, there is no way to provide the OAuth2 CLIENT_SECRET and COOKIE_SECRET from the secret kind.  I use ARGOCD to manage Testkube installation and store the manifest in a Git repo. Anyone having access to the repo will be able to see the values.

It'd be great if the helm chart loads the values from a secret if provided.

I can take a stab and submit a pull request.

https://github.com/kubeshop/helm-charts/blob/c36e700d5bb143d506b738f91f920344701b6d28/charts/testkube-dashboard/templates/oauth2-deployment.yaml#L56

https://github.com/kubeshop/helm-charts/blob/c36e700d5bb143d506b738f91f920344701b6d28/charts/testkube-dashboard/templates/oauth2-deployment.yaml#L61

**Comment by vsukhin** [comment]
thank you @thehundt good question, please discuss it with @ypoplavs

**Comment by ypoplavs** [comment]
Hi @thehundt!
Thank you for a request. I have created a [PR](https://github.com/kubeshop/helm-charts/pull/582) for adding secrets to OAuth2 deployment. Please review and let me know if anything is missing.

**Comment by thehundt** [comment]
@ypoplavs Looks good! Thank you!
