### ISSUE TITLE
Manage job-template.yaml from values.yaml

### ISSUE THREAD

**Issue by artem-zherdiev-ingio** [kubeshop/helm-charts#584]
**Describe the bug**
It seems .Values.configValues parameter breaks job-template.yaml. It can't run test after updates.

**To Reproduce**
1. Copy content from job-template.yaml and paste to .Values.configValues like:
`
.Values.configValues: |
    <here content from the file>
`
Or use example from values.yaml
2. Try to run test

**Expected behavior**
Ability to configure job-template.yaml from values.yaml for adding any of job or job container spec. Or ability to somehow load self job-tepmlate from self chart using testkube as dependency chart.

**Version / Cluster**
- Version 1.13.11
- GKE
- 1.24

Related to: https://discord.com/channels/884464549347074049/885185660808474664/1130494644573175858

**Comment by artem-zherdiev-ingio** [comment]
Hey, I am only started use testkube, so not familiar with it, so questions:
1. I am using prebuilded k6 executor, so, I will need my own custom one in that case?
2. How to do it?

Thanks

**Comment by vsukhin** [comment]
1.You just need your own copy of k6-executor CRD with yourr own jobTemplate field
2. [You can create your testusing C](http://docs.testkube.io/articles/creating-tests#changing-the-default-job-template-used-for-test-execution)
3. Yes, will check configValues

**Comment by artem-zherdiev-ingio** [comment]
My bad, configValues works as expected. Sorry for the noise.
