### ISSUE TITLE
Allow extension of oauth2-proxy environment variables with envFrom user provided Secret or ConfigMap

### ISSUE THREAD

**Issue by hobti01** [kubeshop/helm-charts#611]
**Describe the enhancement you'd like to see**
Allow reference of Secret or ConfigMap to provide multiple environment variables.  This allows deployers of the Helm Chart to manage multiple sensitive or non-sensitive values without needing to override or modify multiple default values.

**Additional context**
* The current configuration of the `oauth2` deployment allows sensitive values for only a few "well-known" properties.  These well-known properties require configuration of pairs of values (Secret name and key name) for each value, which is flexible yet less convenient than specifying a single user-provided Secret.
* Arrays do not lend themselves to extension in Helm.  The current extension point of `extraEnvVars` provides a single level of extension, but when including testkube in another chart this extension point loses effectiveness.  In wrapper or umbrella charts, maps or other value arrangements can be used to create a Secret or ConfigMap that is "plugged in" to the testkube Chart.
* The current configuration can be "hacked" to template an `envFrom` construction into the deployment template due to the use of `{{ include "global.tplvalues.render" (dict "value" .Values.oauth2.extraEnvVars "context" $) | nindent 8 | trim }}` at the end of the variable list. However we recognise this as a misuse of the intention of `extraEnvVars` and would like to avoid it.
```yaml
extraEnvVars:
  envFrom:
    - secretRef:
        name: my-secret-name
```

This enhancement, focused only on the oauth2-proxy deployment, places conditions around existing env variables so that entries are only created when values exist, instead of always creating empty values directly within `env` which override any values added via `envFrom`.  Then an `extraEnvFrom` value is used to explicitly add the `envFrom:` section to the deployment. 
 This approach maintains compatibility with existing use.

> A more comprehensive and preferable (from our perspective) rework of environment variables would be to use maps/dicts for env variables so that each variable can be overridden individually at any level of chart inheritance.

**Comment by vsukhin** [comment]
done
