### ISSUE TITLE
Ability to set pod annotations on testkube pre-upgrade job

### ISSUE THREAD

**Issue by gavinclarkeuk** [kubeshop/helm-charts#624]
Need the ability to set annotations on the  pre-upgrade jobs podspec in the testkube chart. If running in a namespace with linkerd jobs will hang forever unless it is possible to set the annotation `"linkerd.io/inject": disabled`. Currently this is possible for other Jobs, but not the main pre-upgrade job.

**Comment by vsukhin** [comment]
@ypoplavs please check

**Comment by vsukhin** [comment]
done
