### ISSUE TITLE
Make cronjob-template.yaml overridable

### ISSUE THREAD

**Issue by cedricmckinnie** [kubeshop/helm-charts#640]
**Describe the enhancement you'd like to see**
Cannot override cronjob-template.yaml to set image registry in isolation. Using `.global.imageRegistry` does not work because it overrides every image registry in all charts just to set `TESTKUBE_REGISTRY` environment variable for cronjob generation. I would like to be able to override using different registries for various images.

**Additional context**
Possible solutions:
- Make entire cronjob-template.yaml overridable similar to executors via base64 encoded environment variable.
- Cronjob template vars could be overridable as helm vars and default to originals. Perhaps: `{{ testkube-operator.Values.cronjob.registry | default .Registry }}` etc.?

**Comment by cedricmckinnie** [comment]
Just realized that I can overwrite `test.spec.executionRequest.cronJobTemplate` but is there a cleaner way to do so without having to hard-code the template into every test? Perhaps cronJobTemplateReference to a custom configmap?

Seems like `executor.spec.job_template` would not work because the cronjob template must be correlated with a test so that it can include `.Schedule` var into the template.

**Comment by cedricmckinnie** [comment]
Looks like the new Template CRD was added [3 weeks ago](https://github.com/kubeshop/testkube-operator/pull/173) and a release hasn't been cut yet. The solution for me here is to use `.cronJobTemplateReference` but the CRD is not available in v1.14.0 which I'm currently pinned to. 

Out of curiosity, are you all planning a release soon? Would it make sense to cut a production release before including this feature in the main docs? Looks like it's currently only on the `develop` branch of `testkube-operator` repo.

https://docs.testkube.io/articles/templates/

As always - fantastic tool and thank you!

**Comment by vsukhin** [comment]
hey, @cedricmckinnie 
You can do it using a few approaches
1.  cronJobTemplate - it will modify default cron job template for each test you use it
2.  cronJobTemplateReference - it will use a full cron job template for each test you use it (upgrade to latest Testkube 1.14.5)
3. you can update defaault cron job template in in configmap or before installation

**Comment by vsukhin** [comment]
closing for now, hope, above options should be enough
