### ISSUE TITLE
global.imageRegistry is not taken into account for all images

### ISSUE THREAD

**Issue by sylock** [kubeshop/helm-charts#653]
**Describe the bug**
Defining the global.imageRegistry does not prefix a few images. When installing testkube off internet, it fails the installation since it cannot retrieve these images.

**To Reproduce**
Make a template, and see that in the template, you still have some images since the imageRegistry value:

```bash
helm template   testkube-development kubeshop/testkube   --namespace testkube-development   --set global.imageRegistry=myregistry.com | grep image: | grep -v myregistry.com
```

You see these images not prefixed with the configured global.imageRegistry:

```bash
        image: natsio/nats-box:0.13.2
        image: nats:2.9.8-alpine
        image: natsio/nats-server-config-reloader:0.7.4
        image: natsio/prometheus-nats-exporter:0.10.1
    image: synadia/nats-box
      image: busybox
      image: busybox
      image: busybox
```

**Expected behavior**
Setting the global.imageRegistry must configure all images and not part of them.

**Version / Cluster**
Helm Chart Version v1.14.9
 
**Additional context**
We are installing testkube on-premise, without a direct access to internet and repos, but using an Artifactory as a proxy.

**Comment by vsukhin** [comment]
thank you @sylock please take a look at it @ypoplavs

**Comment by ypoplavs** [comment]
Hello @sylock!
NATS is a third-party chart that we rely on and, therefore, it requires passing image registry differently than in Testkube. You can use `--set` or provide the image registries in `values.yaml` file. Example of using `--set`:
```
--set nats.nats.image.registry=REGISTRY_NAME --set nats.natsbox.image.registry=REGISTRY_NAME  --set nats.reloader.image.registry=REGISTRY_NAME  --set nats.exporter.image.registry=REGISTRY_NAME
```

**Comment by ypoplavs** [comment]
Miss from our side. We will update the docs. Apologies for the inconvenience @sylock !

**Comment by sylock** [comment]
If I can help tell me what/where. I can make a change proposal to the doc (but please give me some guidelines).

**Comment by ypoplavs** [comment]
hi @sylock! Thank you for offer, however I have already updated the docs. Could you please take a look and give your feedback: https://docs.testkube.io/articles/deploying-from-private-registries?
If there is something missing, please feel free to submit a PR with changes :)

**Comment by smals-vinve** [comment]
Hello @ypoplavs I've tested the new documentation in a disconnected cluster and that works now if we additionally set the registry for nats. Thanks!
