### ISSUE TITLE
testkube-operator-controller-manager proxy container image doesn't support arm64

### ISSUE THREAD

**Issue by maxforasteiro** [kubeshop/helm-charts#686]
**Describe the bug**
`kubebuilder/kube-rbac-proxy:v0.8.0` doesn't support arm64 (support was added on v2.0.1 according to [this](https://github.com/kubernetes-sigs/kubebuilder/commit/b025968447fae13ce2ae3e8f301a2fbb333a2bd4). When testkube-operator-controller-manager runs in an arm64 node, it stays in crashloopbackoff state with `exec user process caused "exec format error"` error message.

**To Reproduce**
1. deploy a testkube-operator in a cluster with only arm64 nodes without changing any of the defaults values.

**Expected behavior**
to have testkube-operator-controller-manager running fine in an arm64 node.

**Version / Cluster**
- Which testkube version? `testkube-operator-1.16.11`
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.27

**Screenshots**
 
**Additional context**

**Comment by vsukhin** [comment]
thank you @maxforasteiro pinging @ypoplavs
