### ISSUE TITLE
feat: (testkube-api) All job templates should be configurable as cleartext

### ISSUE THREAD

**Issue by bkomraz1** [kubeshop/helm-charts#696]
**Is your feature request related to a problem? Please describe.**
Unfortunate job-container-template.yml and job-scraper-template.yml can't be configured in the way as job-template.yml may be configured as clear text.

**Describe the solution you'd like**
Support jobContainerTemplate and jobScraperTemplate helm chart values that overwrite content of  job-container-template.yml and job-scraper-template.yml files used for rendering testkube-api config map

**Comment by vsukhin** [comment]
thank you @bkomraz1 we will think about ut

**Comment by bkomraz1** [comment]
@vsukhin The pull request is ready: #697 
You need just review it.

**Comment by vsukhin** [comment]
@bkomraz1 have you looked at pr questions?

**Comment by ypoplavs** [comment]
PR was merged.
