### ISSUE TITLE
apiServerEndpoint and internal cluster svc

### ISSUE THREAD

**Issue by dmitry-mightydevops** [kubeshop/helm-charts#706]
**Describe the enhancement you'd like to see**
What functionality is available behind `apiServerEndpoint` assuming testkube dashboard is available behind teleport and has no authentication via oauth2? Am I correct in understanding that exposing `apiServerEndpoint`  via ingress would add security issues, as potential attacker can use public API calls to run tests (or see some valuable data over api)

**Additional context**

I have tried to use internal service, but it didn't work the way I expected without custom networking routing into kubernetes dns
![image](https://github.com/kubeshop/helm-charts/assets/70822710/3cc45c8a-a8ad-49d7-be75-781d9eb196a6)

### versions:
aws eks 1.27
docker.io/kubeshop/testkube-api-server:1.16.22
docker.io/kubeshop/testkube-dashboard:1.16.2

**Comment by vsukhin** [comment]
thank you @dmitry-mightydevops good question, guess @ypoplavs can answer

**Comment by ypoplavs** [comment]
Hello @dmitry-mightydevops!
The dashboard is accessing API server from the browser, not from the pod, thus, it is not reachable for you.

We have not tried to use teleport with Testkube, however I assume that without configuring oauth2 API will be a vulnerable point.
