### ISSUE TITLE
Allow PathType for ingress to be defined other than Prefix

### ISSUE THREAD

**Issue by fulgas** [kubeshop/helm-charts#709]
From Kubernetes 1.22, i think, the  the PathType on the Ingress needs to be `ImplementationSpecific` when using regex.

https://kubernetes.github.io/ingress-nginx/faq/#validation-of-path

> When "ingress.spec.rules.http.pathType=Exact" or "pathType=Prefix", this validation will limit the characters accepted on the field "ingress.spec.rules.http.paths.path", to "alphanumeric characters", and "/," "_," "-." Also, in this case, the path should start with "/."
> 
> When the ingress resource path contains other characters (like on rewrite configurations), the pathType value should be "ImplementationSpecific".

**Comment by vsukhin** [comment]
thank you @fulgas for @ypoplavs to check it out
