### ISSUE TITLE
Custom cronjobs template

### ISSUE THREAD

**Issue by jaceksocha** [kubeshop/helm-charts#753]
Hi

Is there a known way to overwrite global cronjob template?

I saw only use case with "create-test" api call https://docs.testkube.io/articles/creating-tests/#changing-the-default-cronjob-template-used-for-scheduled-test-execution but it is required in every api call and IU does not support it (afaik).

Greetings

**Comment by vsukhin** [comment]
hey @jaceksocha I beleive @ypoplavs should add it to values.yml

**Comment by jaceksocha** [comment]
Thank you for fast reaction.
When do you plan to release chart ?

Greetings

**Comment by vsukhin** [comment]
@ypoplavs ?

**Comment by ypoplavs** [comment]
@jaceksocha let me discuss this with the team.

**Comment by jaceksocha** [comment]
@ypoplavs of course.
I will be grateful for message if you future knew something in this case.

Greetings

**Comment by ypoplavs** [comment]
Hello @jaceksocha!
The change was released. Please upgrade to the latest helm chart version.

**Comment by jaceksocha** [comment]
Thank you @ypoplavs , we are testing new chart `1.16.51`.

The chart has been deployed with:

`
      ...
      cronJobTemplate: |+
        apiVersion: batch/v1
          kind: CronJob
          metadata:
            name: "{{ .Name }}"
            namespace: {{ .Namespace }}
            labels:
              testkube: {{ .ResourceURI }}
          {{- if .ArgoCDSync }}
          ownerReferences:
            - apiVersion: tests.testkube.io/{{ .Version }}
              kind: {{ .Resource }}
              name: {{ .Id }}
              uid: {{ .UID }}
          {{- end }}
          spec:
            schedule: "{{ .Schedule }}"
            concurrencyPolicy: Forbid
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: curlimage
                        {{- if .Registry }}
                        image: {{ .Registry }}/curlimages/curl
                        {{- else }}
                        image: curlimages/curl
                        {{- end }}
                        imagePullPolicy: IfNotPresent
                        command:
                          - sh
                          - -c
                        args:
                          - 'curl -X POST -H "Content-Type: application/json" -d ''{{ .Data }}'' "http://{{ .ServiceName }}:{{ .ServicePort}}/v1/{{ .ResourceURI }}/{{ .Id }}/executions"'
                    restartPolicy: Never
                    nodeSelector:
                      nodegroup/namespace: testkube
                    tolerations:
                      - key: dedicated
                        value: testkube
                        effect: NoSchedule
                backoffLimit: 0
                ttlSecondsAfterFinished: 180`

with result success.
 
Checking on pods:
` k describe pod testkube-operator-controller-manager-xyz`

seems to have proper environment variables

`    Environment:
      APISERVER_FULLNAME:          testkube-api-server
      APISERVER_PORT:              8088
      APISERVER_TEMPLATE_CRONJOB: CAgIGFwaVZlcnNpb246IGJhdGNoL3YxCiAgICAgICAga2luZDogQ3JvbkpvYgogICAgICAgIG1ldGFkYXRhOgogICAgICAgICAgbmFtZTogInt7IC5OYW1lIH19IgogICAgICAgICAgbmFtZXNwYWNlOiB7eyAuTmFtZXNwYWNlIH19CiAgICAgICAgICBsYWJlbHM6CiAgICAgICAgICAgIHRlc3RrdWJlOiB7eyAuUmVzb3VyY2VVUkkgfX0KICAgICAgICB7ey0gaWYgLkFyZ29DRFN5bmMgfX0KICAgICAgICBvd25lclJlZmVyZW5jZXM6CiAgICAgICAgICAtIGFwaVZlcnNpb246IHRlc3RzLnRlc3RrdWJlLmlvL3t7IC5WZXJzaW9uIH19CiAgICAgICAgICAgIGtpbmQ6IHt7IC5SZXNvdXJjZSB9fQogICAgICAgICAgICBuYW1lOiB7eyAuSWQgfX0KICAgICAgICAgICAgdWlkOiB7eyAuVUlEIH19CiAgICAgICAge3stIGVuZCB9fQogICAgICAgIHNwZWM6CiAgICAgICAgICBzY2hlZHVsZTogInt7IC5TY2hlZHVsZSB9fSIKICAgICAgICAgIGNvbmN1cnJlbmN5UG9saWN5OiBGb3JiaWQKICAgICAgICAgIGpvYlRlbXBsYXRlOgogICAgICAgICAgICBzcGVjOgogICAgICAgICAgICAgIHRlbXBsYXRlOgogICAgICAgICAgICAgICAgc3BlYzoKICAgICAgICAgICAgICAgICAgY29udGFpbmVyczoKICAgICAgICAgICAgICAgICAgICAtIG5hbWU6IGN1cmxpbWFnZQogICAgICAgICAgICAgICAgICAgICAge3stIGlmIC5SZWdpc3RyeSB9fQogICAgICAgICAgICAgICAgICAgICAgaW1hZ2U6IHt7IC5SZWdpc3RyeSB9fS9jdXJsaW1hZ2VzL2N1cmwKICAgICAgICAgICAgICAgICAgICAgIHt7LSBlbHNlIH19CiAgICAgICAgICAgICAgICAgICAgICBpbWFnZTogY3VybGltYWdlcy9jdXJsCiAgICAgICAgICAgICAgICAgICAgICB7ey0gZW5kIH19CiAgICAgICAgICAgICAgICAgICAgICBpbWFnZVB1bGxQb2xpY3k6IElmTm90UHJlc2VudAogICAgICAgICAgICAgICAgICAgICAgY29tbWFuZDoKICAgICAgICAgICAgICAgICAgICAgICAgLSBzaAogICAgICAgICAgICAgICAgICAgICAgICAtIC1jCiAgICAgICAgICAgICAgICAgICAgICBhcmdzOgogICAgICAgICAgICAgICAgICAgICAgICAtICdjdXJsIC1YIFBPU1QgLUggIkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbiIgLWQgJyd7eyAuRGF0YSB9fScnICJodHRwOi8ve3sgLlNlcnZpY2VOYW1lIH19Ont7IC5TZXJ2aWNlUG9ydH19L3YxL3t7IC5SZXNvdXJjZVVSSSB9fS97eyAuSWQgfX0vZXhlY3V0aW9ucyInCiAgICAgICAgICAgICAgICAgIHJlc3RhcnRQb2xpY3k6IE5ldmVyCiAgICAgICAgICAgICAgICAgIG5vZGVTZWxlY3RvcjoKICAgICAgICAgICAgICAgICAgICByYXNwLm5vZGVncm91cC9uYW1lc3BhY2U6IHRlc3RrdWJlCiAgICAgICAgICAgICAgICAgIHRvbGVyYXRpb25zOgogICAgICAgICAgICAgICAgICAgIC0ga2V5OiBkZWRpY2F0ZWQKICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiB0ZXN0a3ViZQogICAgICAgICAgICAgICAgICAgICAgZWZmZWN0OiBOb1NjaGVkdWxlCiAgICAgICAgICAgICAgYmFja29mZkxpbWl0OiAwCiAgICAgICAgICAgICAgdHRsU2Vjb25kc0FmdGVyRmluaXNoZWQ6IDE4MA==`

base64 decoded value of APISERVER_TEMPLATE_CRONJOB returns value same as template, but cronjob are not created

`k get cronjob
No resources found in testkube namespace.
`

Did not see any errors related in eks and testkube logs.


Maybe we passing template value in wrong way, have you encountered such behavior ?

Greetings

**Comment by ypoplavs** [comment]
Thanks for raising @jaceksocha! I will check that

**Comment by vsukhin** [comment]
@ypoplavs ?

**Comment by vsukhin** [comment]
?
