### ISSUE TITLE
Add capability to limit the ValidatingWebhookConfiguration to a single namespace.

### ISSUE THREAD

**Issue by plamen-kutinchev** [kubeshop/helm-charts#760]
**Is your feature request related to a problem? Please describe.**
We would like to limit the validating webhook: https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube-operator/templates/webhook.yaml to a single namespace.

**Describe the solution you'd like**
We could probably use namespaceSelector to limit the webhook: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector.

**Comment by plamen-kutinchev** [comment]
I see the PR is merged, do we have a release I can start using or we need to wait for something more to be added ? Thank you for the PR 🙇

**Comment by ypoplavs** [comment]
Hello @plamen-kutinchev!
Apologies for the delay, the feature has been released in `1.16.60`
