### ISSUE TITLE
Add the possibility to globally set tolerations and nodeSelector

### ISSUE THREAD

**Issue by lakostin** [kubeshop/helm-charts#787]
**Describe the enhancement you'd like to see**
Now it is necessary to set tolerations and nodeSelectors for each component (dashboard, api, mongo...) as well as for executors via the job template. It would be cool to have an ability to set it globally for everything to avoid copypaste.

**Comment by ypoplavs** [comment]
Pushed changes for tolerations and nodeSelectors to develop. @vsukhin could you please update job Templates?

**Comment by vsukhin** [comment]
created pr
