### ISSUE TITLE
testkube-playwright-executor error on arm64/aarch64

### ISSUE THREAD

**Issue by jaceksocha** [kubeshop/helm-charts#790]
**Describe the bug**
We are running Testkube helm chart version: 1.16.51. Cypress executor seems to works fine, the problem is with playwright executor when using arm based eks nodes (when working on X86_64 based nodes  everything works fine)

**To Reproduce**
1. Run 'install testkube helm chart version 1.16.51'
2. Specify 'create and launch playwright test '
3. See error:
```
 kubectl get pod
NAME                                                    READY   STATUS       RESTARTS      AGE
66042bbb0c909043e719134d-blgsz                          0/1     Init:Error   0             3s
```

```
kubectl logs 66042bbb0c909043e719134d-blgsz
Defaulted container "66042bbb0c909043e719134d" out of: 66042bbb0c909043e719134d, 66042bbb0c909043e719134d-init (init)
Error from server (BadRequest): container "66042bbb0c909043e719134d" in pod "66042bbb0c909043e719134d-blgsz" is waiting to start: PodInitializing
```

**Expected behavior**
Playwright executor is able to launch on arm based architectures.

**Version / Cluster**
- testkube version : 1.16.51
- Kubernetes cluster: EKS
- Kubernetes version: 1.26

 
**Additional context**
Additional informations:
watching on job
```
kubectl get job
NAME                       COMPLETIONS   DURATION   AGE
66042bbb0c909043e719134d   0/1           95s        95s


k describe job 66042bbb0c909043e719134d
Name:             66042bbb0c909043e719134d
....
  Containers:
   66042bbb0c909043e719134d:
    Image:      kubeshop/testkube-playwright-executor:285642b
    Port:       <none>

```
I found the attempt to download testkube-playwright-executor image with tag "**285642b**", which I see is only available for amd64 architecture : https://hub.docker.com/layers/kubeshop/testkube-playwright-executor/285642b/images/sha256-8984fc01133cc9aca79afcb43612dd3e021ff0dea8e8e90869e5ebb4da967e49?context=explore

Can you help with this issue ?

Greetings

**Comment by vsukhin** [comment]
hey @jaceksocha this is a question for @ypoplavs

**Comment by ypoplavs** [comment]
Hello @jaceksocha!

ARM-based images have semsev or package names as tags. Please check Dockerhub for more.
<img width="606" alt="Screenshot 2024-04-02 at 13 32 30" src="https://github.com/kubeshop/helm-charts/assets/45286051/1910ea5a-3814-46c6-8e34-8b5182af0c4d">

Commit sha tags are used internally and do not support ARM.

**Comment by jaceksocha** [comment]
Hi @ypoplavs 

Is it possible to chage this behaviour (set proper image tags for executors) in helm chart ?

Afaik we do not have any modifications related to registries or images in helm chart, so it seems to bee a default.

Greetings

**Comment by ypoplavs** [comment]
Hey @jaceksocha!
By default we use semver tags for Docker images: https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/executors.json#L72

Please let me know what version of helm charts you use. I will check it.

**Comment by jaceksocha** [comment]
Thanks for fast reaction, we are using 1.16.51.

**Comment by ypoplavs** [comment]
Sure! I have just checked `1.16.51` and there's a wrong configuration in executors.json file, could you please upgrade to `1.16.52`. This issue won't happen with this version.

**Comment by jaceksocha** [comment]
Got it! We will make an upgrade to 1.16.52 and let you know if it solves the problem.

**Comment by jaceksocha** [comment]
1.16.52 do the job :)

Thank you @ypoplavs
