### ISSUE TITLE
Missing namespace on resources

### ISSUE THREAD

**Issue by rd-michael-pasdziernik** [kubeshop/helm-charts#957]
**Describe the bug**
Several resources are missing the namespace in the templates, for example [here](https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/templates/role.yaml). These resources go to default namespace when resources are rendered with `helm template --namespace "testing"`

**Expected behavior**
All resources are deployed to the same namespace.

**Comment by vsukhin** [comment]
hey @rd-michael-pasdziernik thank you for reporting, let our devops team to check it out @ypoplavs

**Comment by rd-michael-pasdziernik** [comment]
Thank you for looking at this. After looking at the best practices discussion we now set the namespace via kubectl after templating.
